name: Deploy Main

on:
  workflow_run:
    workflows: ["Build Main"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: main.yml
        branch: main
        name: pi-app-deployer-agent_${{ github.sha }}
    - name: Display structure of downloaded files
      run: ls -R
