name: Deploy Main

on:
  workflow_run:
    workflows: ["Build Main"]
    branches: [main]
    types:
      - completed

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: pi-app-deployer-agent_${{ github.sha }}
    - name: Display structure of downloaded files
      run: ls -R
