name: Validation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Deploy Heroku Production
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        GITHUB_SHA:  ${{ github.sha }}
        SERVER_API_KEY: ${{ secrets.SERVER_API_KEY_PROD }}
      run: ./.github/scripts/deploy-heroku.sh pi-app-deployer
    - name: Integration
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        GH_COMMIT_TOKEN: ${{ secrets.GH_COMMIT_TOKEN }}
      run: |
        loginctl enable-linger runner
        sleep 2
        make test-integration
